import { z } from "zod";

export const addMemberSchema = z.object({
  userId: z.string().min(30, "User ID is minimum 30 characters long"),
  greeting: z.string(),
  firstName: z.string(),
  lastName: z.string(),
  email: z.string().email("Invalid email address"),
  phoneNumber: z.string(),
  address: z.string(),
  city: z.string(),
  state: z.string().optional(),
  zipCode: z.string(),
  petitioner1: z.string().optional(),
  petitioner2: z.string().optional(),
  petitioner3: z.string().optional(),
  memberStatus: z.string().optional(),
});

export const editFormSchema = z.object({
  memberId: z.string(),
  firstName: z.string().min(1, "First name is required"),
  middleName: z.string().optional(),
  lastName: z.string().min(1, "Last name is required"),
  emailAddress: z.string().email("Invalid email address"),
  password: z.string().optional(),
  phoneNumber: z.string(),
  address: z.string(),
  city: z.string(),
  state: z.string(),
  zipcode: z.string(),
  petitioner1: z.string(),
  petitioner2: z.string(),
  petitioner3: z.string(),
  memberStatus: z.string(),
  chapterOffice: z.string(),
  grandChapterOffice: z.string(),
  memberRank: z.string(),
  birthdate: z.string(),
  initiationDate: z.string().optional(),
  queenOfTheSouth: z.string().optional(),
  amarant: z.string().optional(),
  petitionDate: z.string().optional(),
  petitionReceived: z.string().optional(),
  demitIn: z.string().optional(),
  demitOut: z.string().optional(),
  demitToChapter: z.string().optional(),
  investigationDate: z.string().optional(),
  investigationAcceptReject: z.string().optional(),
  enlightenedDate: z.string().optional(),
  droppedDate: z.string().optional(),
  dropReason: z.string(),
  suspensionExpelledDate: z.string().optional(),
  suspensionExpelledReason: z.string(),
  reinstatedDate: z.string().optional(),
  dateOfDeath: z.string().optional(),
  actualDateOfDeath: z.string().optional(),
  placeOfDeath: z.string().optional(),
  emergencyContact: z.string(),
  emergencyContactPhone: z.string(),
  secretaryNotes: z.string().optional(),
});
